apiVersion: node-js/v1
kind: Deployment
metadata:
  name: Kubectl deployment
spec:
  selector:
    matchLabels:
      app: node-js
  replicas: 1
  template:
    metadata:
      labels:
        app: node-js
    spec:
      containers:
        - name: node-js
          image: smatys300/coursework2:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: node-js
spec:
  selector:
    app: node-js
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort
